name = "Server"
version = "0.1.0"
defaultTargets = ["server"]

[[lean_lib]]
name = "Solver"

[[lean_exe]]
name = "server"
root = "Main"

[[lean_exe]]
name = "lean_http_server"
root = "LeanHttpServer"
