name = "Untitled"
version = "0.1.0"
defaultTargets = ["untitled"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Untitled"

[[lean_exe]]
name = "untitled"
root = "Main"

[[lean_exe]]
name = "lean_http_server"
root = "LeanHttpServer"
